#! /bin/sh

# copy source to temporary folders
rm -rf /tmp/testc
mkdir /tmp/testc

IFS=" "
FTOLINK=( $3 )
echo 
for f in "${FTOLINK[@]}"
do
	cat ~/42-testc/functions/$f.c | sed -e "s/F_TO_REPLACE()/$2/g" > /tmp/testc/$f.c -e "s/F_ARG/$2/g" -e "s/A1/$4/g" -e "s/A2/$5/g" > /tmp/testc/$f.c
	echo "compiling $f.c"
	gcc -c /tmp/testc/$f.c
	echo "copying $f.o to /tmp/testc\n"
	mv $f.o /tmp/testc/$f.o
done

# check norm
norminette --CheckForbiddenSourceHeader $1

if [ $? -eq 0 ] 
then
	gcc -Wall -Werror -Wextra -o /tmp/testc/test $1 /tmp/testc/*.o
	if [ $? -ne 0 ]
	then echo "compile KO"
	else 
		echo "compile OK\n"
		echo "running $2"
		chmod +x /tmp/testc/test
		/tmp/testc/test
	fi
fi
